#ifndef __pp2_defines_h
#define __pp2_defines_h

//yyyyyyyyyyyyyyyyyyyyyyy
// CONFIG_XXX_PP2 Definitions from lk-3.10.70-15t1 after performing 'make mvebu_lsp_defconfig'
#define CONFIG_MVPP2_DEBUG
#define CONFIG_MV_ETH_PP2
#define CONFIG_MV_ETH_INCLUDE_PHY
#define CONFIG_MV_ETH_PP2_CLS2
#define CONFIG_MV_ETH_PP2_CLS3
#define CONFIG_MV_ETH_PP2_CLS4
#define CONFIG_MV_ETH_PP2_CLS_MC
// PP2 BM configuration
#define CONFIG_MV_PP2_BM_LONG_BUF_NUM 1024
#define CONFIG_MV_PP2_BM_SHORT_BUF_NUM 2048
// PP2 Rx/Tx Queue configuration
#define CONFIG_MV_PP2_RXQ 8
#define CONFIG_MV_PP2_TXQ 8
#define CONFIG_MV_PP2_RXQ_DESC 256
#define CONFIG_MV_PP2_RXQ_DEF 0
#define CONFIG_MV_PP2_TXQ_DESC 1024
#define CONFIG_MV_PP2_TXQ_DEF 0
#define CONFIG_MV_PP2_TXQ_CPU_CHUNK 64
#define CONFIG_MV_PP2_AGGR_TXQ_SIZE 256
#define CONFIG_MV_PP2_TEMP_TXQ_SIZE 512
#define CONFIG_MV_PP2_TEMP_TXQ_HWF_SIZE 256
// PP2 Control and Statistics
#define CONFIG_MV_PP2_DEBUG_CODE
#define CONFIG_MV_PP2_STAT_ERR
#define CONFIG_MV_PP2_STAT_INF
#define CONFIG_MV_PP2_STAT_DBG
// PP2 Advanced Features
#define CONFIG_MV_PP2_TXDONE_PROCESS_METHOD
#define CONFIG_MV_PP2_TXDONE_IN_HRTIMER
#define CONFIG_MV_PP2_TX_DONE_HIGH_RES_TIMER_PERIOD 1000
#define CONFIG_MV_PP2_TXDONE_COAL_PKTS 16
#define CONFIG_MV_PP2_RX_COAL_PKTS 32
#define CONFIG_MV_PP2_RX_COAL_USEC 100
#define CONFIG_MV_PP2_RX_POLL_WEIGHT 64
#define CONFIG_MV_PP2_EXTRA_BUF_SIZE 120
#define CONFIG_MV_PP2_EXTRA_BUF_NUM 1024

#endif

